POST http://localhost:8080/account/login
Content-Type: application/json

{
  "email": "m1.swaanen@hotmail.com",
  "password": "1234"
}

###

POST http://localhost:8080/account/register
Content-Type: application/json

{
  "name": "Michiel Swaanen",
  "email": "m2.swaanen@hotmail.com",
  "password": "1234",
  "passwordConfirmation": "1234"
}

###

GET http://localhost:8080/account/fetch/100
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im0xLnN3YWFuZW5AaG90bWFpbC5jb20iLCJleHBpcmVzQXQiOjE1NzYxNzQzMDEsImlkIjowLCJsb2dpbkF0Ijp7InNlY29uZHMiOjE1NzYxNzM0MDEsIm5hbm9zIjo5Njc3NDUwMDB9LCJuYW1lIjoiTWljaGllbCBTd2FhbmVuIn0.r7SxAeXKfBxDDN4-q6N3-gW87hBCY1fKBb47SPfeP1M

###