// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthenticationStatus int32

const (
	AuthenticationStatus_SUCCESS AuthenticationStatus = 0
	AuthenticationStatus_FAILED  AuthenticationStatus = 1
)

var AuthenticationStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILED",
}

var AuthenticationStatus_value = map[string]int32{
	"SUCCESS": 0,
	"FAILED":  1,
}

func (x AuthenticationStatus) String() string {
	return proto.EnumName(AuthenticationStatus_name, int32(x))
}

func (AuthenticationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

type AccountLoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountLoginRequest) Reset()         { *m = AccountLoginRequest{} }
func (m *AccountLoginRequest) String() string { return proto.CompactTextString(m) }
func (*AccountLoginRequest) ProtoMessage()    {}
func (*AccountLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *AccountLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountLoginRequest.Unmarshal(m, b)
}
func (m *AccountLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountLoginRequest.Marshal(b, m, deterministic)
}
func (m *AccountLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountLoginRequest.Merge(m, src)
}
func (m *AccountLoginRequest) XXX_Size() int {
	return xxx_messageInfo_AccountLoginRequest.Size(m)
}
func (m *AccountLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountLoginRequest proto.InternalMessageInfo

func (m *AccountLoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccountLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AccountLoginResponse struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	LoginAt              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=loginAt,proto3" json:"loginAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AccountLoginResponse) Reset()         { *m = AccountLoginResponse{} }
func (m *AccountLoginResponse) String() string { return proto.CompactTextString(m) }
func (*AccountLoginResponse) ProtoMessage()    {}
func (*AccountLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *AccountLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountLoginResponse.Unmarshal(m, b)
}
func (m *AccountLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountLoginResponse.Marshal(b, m, deterministic)
}
func (m *AccountLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountLoginResponse.Merge(m, src)
}
func (m *AccountLoginResponse) XXX_Size() int {
	return xxx_messageInfo_AccountLoginResponse.Size(m)
}
func (m *AccountLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountLoginResponse proto.InternalMessageInfo

func (m *AccountLoginResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountLoginResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccountLoginResponse) GetLoginAt() *timestamp.Timestamp {
	if m != nil {
		return m.LoginAt
	}
	return nil
}

type AccountRegisterRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirmation string   `protobuf:"bytes,4,opt,name=passwordConfirmation,proto3" json:"passwordConfirmation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRegisterRequest) Reset()         { *m = AccountRegisterRequest{} }
func (m *AccountRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRegisterRequest) ProtoMessage()    {}
func (*AccountRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *AccountRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRegisterRequest.Unmarshal(m, b)
}
func (m *AccountRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRegisterRequest.Marshal(b, m, deterministic)
}
func (m *AccountRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRegisterRequest.Merge(m, src)
}
func (m *AccountRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRegisterRequest.Size(m)
}
func (m *AccountRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRegisterRequest proto.InternalMessageInfo

func (m *AccountRegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountRegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccountRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AccountRegisterRequest) GetPasswordConfirmation() string {
	if m != nil {
		return m.PasswordConfirmation
	}
	return ""
}

type AccountRegisterResponse struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	RegisterAt           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=registerAt,proto3" json:"registerAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AccountRegisterResponse) Reset()         { *m = AccountRegisterResponse{} }
func (m *AccountRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*AccountRegisterResponse) ProtoMessage()    {}
func (*AccountRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *AccountRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRegisterResponse.Unmarshal(m, b)
}
func (m *AccountRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRegisterResponse.Marshal(b, m, deterministic)
}
func (m *AccountRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRegisterResponse.Merge(m, src)
}
func (m *AccountRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_AccountRegisterResponse.Size(m)
}
func (m *AccountRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRegisterResponse proto.InternalMessageInfo

func (m *AccountRegisterResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountRegisterResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccountRegisterResponse) GetRegisterAt() *timestamp.Timestamp {
	if m != nil {
		return m.RegisterAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("services.AuthenticationStatus", AuthenticationStatus_name, AuthenticationStatus_value)
	proto.RegisterType((*AccountLoginRequest)(nil), "services.AccountLoginRequest")
	proto.RegisterType((*AccountLoginResponse)(nil), "services.AccountLoginResponse")
	proto.RegisterType((*AccountRegisterRequest)(nil), "services.AccountRegisterRequest")
	proto.RegisterType((*AccountRegisterResponse)(nil), "services.AccountRegisterResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x36, 0xfd, 0x77, 0x8a, 0x52, 0xd6, 0xa0, 0x21, 0xa0, 0xd6, 0x9c, 0x8a, 0x87, 0x14, 0xaa,
	0x27, 0x6f, 0xa1, 0xb6, 0x22, 0x14, 0x84, 0x44, 0x1f, 0x60, 0x1b, 0xb7, 0x71, 0xa1, 0xd9, 0x8d,
	0xd9, 0x4d, 0x3d, 0xfa, 0x0e, 0xbe, 0x85, 0x6f, 0x29, 0xee, 0x66, 0xb5, 0xb5, 0x55, 0xea, 0x6d,
	0x67, 0xe7, 0x9b, 0x6f, 0xbe, 0x6f, 0x66, 0x60, 0x0f, 0xc7, 0x31, 0x2f, 0x98, 0xf4, 0xb3, 0x9c,
	0x4b, 0x8e, 0x5a, 0x82, 0xe4, 0x0b, 0x1a, 0x13, 0xe1, 0x9e, 0x26, 0x9c, 0x27, 0x73, 0xd2, 0x57,
	0xff, 0xd3, 0x62, 0xd6, 0x97, 0x34, 0x25, 0x42, 0xe2, 0x34, 0xd3, 0x50, 0xef, 0x06, 0x0e, 0x02,
	0x5d, 0x3b, 0xe1, 0x09, 0x65, 0x21, 0x79, 0x2e, 0x88, 0x90, 0xc8, 0x86, 0x3a, 0x49, 0x31, 0x9d,
	0x3b, 0x56, 0xd7, 0xea, 0xed, 0x86, 0x3a, 0x40, 0x2e, 0xb4, 0x32, 0x2c, 0xc4, 0x0b, 0xcf, 0x1f,
	0x9d, 0x8a, 0x4a, 0x7c, 0xc5, 0xde, 0x02, 0xec, 0x55, 0x22, 0x91, 0x71, 0x26, 0x08, 0x42, 0x50,
	0x63, 0x38, 0x25, 0x25, 0x91, 0x7a, 0x7f, 0xb3, 0x57, 0x96, 0xd9, 0x2f, 0xa1, 0x39, 0xff, 0x2c,
	0x0d, 0xa4, 0x53, 0xed, 0x5a, 0xbd, 0xf6, 0xc0, 0xf5, 0xb5, 0x7a, 0xdf, 0xa8, 0xf7, 0xef, 0x8d,
	0xfa, 0xd0, 0x40, 0xbd, 0x37, 0x0b, 0x0e, 0xcb, 0xc6, 0x21, 0x49, 0xa8, 0x90, 0x24, 0x37, 0x26,
	0xb6, 0x6f, 0xbd, 0x6c, 0xac, 0xba, 0x6a, 0x0c, 0x0d, 0xc0, 0x36, 0xef, 0x21, 0x67, 0x33, 0x9a,
	0xa7, 0x58, 0x52, 0xce, 0x9c, 0x9a, 0xc2, 0x6d, 0xcc, 0x79, 0xaf, 0x70, 0xb4, 0xa6, 0xe9, 0xdf,
	0xf3, 0xb8, 0x02, 0xc8, 0xcb, 0xea, 0xad, 0x46, 0xb2, 0x84, 0x3e, 0xef, 0x83, 0x1d, 0x14, 0xf2,
	0x89, 0x30, 0x49, 0x63, 0x25, 0x29, 0x92, 0x58, 0x16, 0x02, 0xb5, 0xa1, 0x19, 0x3d, 0x0c, 0x87,
	0xa3, 0x28, 0xea, 0xec, 0x20, 0x80, 0xc6, 0x38, 0xb8, 0x9d, 0x8c, 0xae, 0x3b, 0xd6, 0xe0, 0xdd,
	0x82, 0xfd, 0x52, 0x72, 0xa4, 0x8f, 0x07, 0x8d, 0xa1, 0xae, 0x56, 0x89, 0x8e, 0x7d, 0x73, 0x4f,
	0xfe, 0x86, 0x5b, 0x71, 0x4f, 0x7e, 0x4b, 0x97, 0x8e, 0xef, 0xa0, 0x65, 0xa6, 0x80, 0xba, 0x6b,
	0xd8, 0x1f, 0x4b, 0x73, 0xcf, 0xfe, 0x40, 0x68, 0xc2, 0x69, 0x43, 0x99, 0xbf, 0xf8, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x26, 0x3a, 0xaa, 0xf9, 0xf6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	Login(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountLoginResponse, error)
	Register(ctx context.Context, in *AccountRegisterRequest, opts ...grpc.CallOption) (*AccountRegisterResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) Login(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountLoginResponse, error) {
	out := new(AccountLoginResponse)
	err := c.cc.Invoke(ctx, "/services.AccountService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Register(ctx context.Context, in *AccountRegisterRequest, opts ...grpc.CallOption) (*AccountRegisterResponse, error) {
	out := new(AccountRegisterResponse)
	err := c.cc.Invoke(ctx, "/services.AccountService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	Login(context.Context, *AccountLoginRequest) (*AccountLoginResponse, error)
	Register(context.Context, *AccountRegisterRequest) (*AccountRegisterResponse, error)
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) Login(ctx context.Context, req *AccountLoginRequest) (*AccountLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAccountServiceServer) Register(ctx context.Context, req *AccountRegisterRequest) (*AccountRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.AccountService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Login(ctx, req.(*AccountLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.AccountService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Register(ctx, req.(*AccountRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AccountService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _AccountService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
